FROM httpd:latest

ARG PROJECT_DOMAIN
ARG PROJECT_ROOT

RUN apt-get update && apt-get install -y vim curl libxml2-dev

RUN apt-get update && apt-get install -y vim mcrypt

RUN apt-get update && apt-get install -y varnish vim && apt-get clean

ADD ./start.sh /start.sh
RUN chmod +x /start.sh

COPY varnish.vcl /etc/varnish/default.vcl
COPY varnish.secret /etc/varnish/varnish.secret

COPY httpd.conf /usr/local/apache2/conf/httpd.conf
COPY httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf

ENV VCL_CONFIG      /etc/varnish/default.vcl
ENV CACHE_SIZE      256M
ENV VARNISHD_PARAMS -a :80 -p workspace_backend=98304 \
        -p http_resp_size=98304 \
        -p http_resp_hdr_len=65536 -s malloc,256m \
        -p default_ttl=3600 -p default_grace=3600 -T 0.0.0.0:6095 -S /etc/varnish/secret

RUN sed -i 's#__PROJECT_DOMAIN__#'"${PROJECT_DOMAIN}"'#g' /usr/local/apache2/conf/httpd.conf
RUN sed -i 's#__PROJECT_ROOT__#'"${PROJECT_ROOT}"'#g' /usr/local/apache2/conf/httpd.conf

#RUN echo "upstream php-upstream { server php:9000; }" > /etc/nginx/conf.d/upstream.conf

EXPOSE 8080 6095

CMD /start.sh